name: Build a docker image

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4 
        with:
          node-version: '18'
          cache: 'npm' # Enable caching for npm dependencies
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            jitsi/jaas-test-wh-proxy:latest
            jitsi/jaas-test-wh-proxy:${{ github.sha }}
